### ISSUE TITLE
Classes don't seems to be transfered to item on Android

### ISSUE THREAD

**Issue by pyreweb2** [RSchwan/com.rolandschwan.iconlabel#2]
Hi,

As the title indicate, the classes don't seems to be setted on the created `#iconLabel` element. Still, the style is applied, weird.

On my app, I added an click event on Alloy, relying on classes to know which button was clicked.

```
<TableView dataCollection="myCollection">
    <TableViewRow onClick="myAction">
        <Label>{{name}}</Label>
        <Widget class="edit" src="com.rolandschwan.iconlabel" text="fa-edit" />
        <Widget class="delete" src="com.rolandschwan.iconlabel" text="fa-trash" />
    </TableViewRow>
</TableView>
```

```
function myAction(event) {
    var target = '';
    if (typeof e.source.id !== 'undefined') {
         if (e.source.id === 'iconLabel') {
              target = e.source.classes[0];
        }
    }

    if (target === 'edit') ...
}
```

On iOS, no problem, it worked, on Android, not.
Inspecting the event.source, classes was empty.

I added a quickfix to your widget, and it seems to do the trick
After `$.iconLabel.text = text;`, line 25

```
if (OS_ANDROID) {
    var classes = args.classes || [];
    $.iconLabel.classes = classes;
}
```

**Comment by RSchwan** [comment]
@Pyreweb If you make a pull request I'll merge it.
PS: Add a comment mentioning this issue.
